---
- name: build docker image
  shell: "docker build -f {{ dockerpath }}/Dockerfile -t http://192.168.122.41:8082/Myapp {{ dockerpath }} "
  #  docker_image:
  # name: Myapp
  # source: build
      # build:
      #   dockerfile: "{{ dockerpath }}/Dockerfile"
        #     path: "{{ dockerpath }}"
        #   pull: no
        # state: "present"
      # force_source: true
      #tags: "http://192.168.122.41:8082/Myapp"
